[package]
name = "host-io"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
arbutil = { path = "../../arbutil/" }
caller-env = { path = "../../caller-env/", default-features = false, features = ["static_caller"] }
