[package]
name = "arbutil"
version = "0.1.0"
edition = "2021"

[dependencies]
digest = "0.9.0"
eyre = "0.6.5"
hex = "0.4.3"
sha3 = "0.10.5"
siphasher = "0.3.10"
wasmparser = "0.95"
serde = { version = "1.0.130", features = ["derive", "rc"] }

[features]
wavm = []
