[package]
name = "prover"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
derivative = "2.2.0"
digest = "0.9.0"
eyre = "0.6.5"
fnv = "1.0.7"
hex = "0.4.3"
libc = "0.2.108"
nom = "7.0.0"
nom-leb128 = "0.2.0"
num = "0.4"
rustc-demangle = "0.1.21"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.67"
sha3 = "0.9.1"
static_assertions = "1.1.0"
structopt = "0.3.23"
serde_with = "1.12.1"
parking_lot = "0.12.1"
lazy_static = "1.4.0"
itertools = "0.10.5"
wat = "1.0.56"
smallvec = { version = "1.10.0", features = ["serde"] }
brotli2 = { version = "0.3.2", optional = true }
rayon = { version = "1.5.1", optional = true }
arbutil = { path = "../arbutil/" }
wasmer = { path = "../tools/wasmer/lib/api/", optional = true }
wasmer-types = { path = "../tools/wasmer/lib/types" }
wasmer-compiler-singlepass = { path = "../tools/wasmer/lib/compiler-singlepass", optional = true, default-features = false, features = ["std", "unwind", "avx"] }
wasmparser = "0.95"

[lib]
name = "prover"
crate-type = ["staticlib", "lib"]

[features]
default = ["native", "rayon", "singlepass_rayon"]
native = ["dep:wasmer", "dep:wasmer-compiler-singlepass", "dep:brotli2"]
singlepass_rayon = ["wasmer-compiler-singlepass?/rayon"]
rayon = ["dep:rayon"]
